Databases:
  RAMC: WAV/{uri}.wav

Protocols:
  RAMC:
    SpeakerDiarization:
      Full:
        scope: file
        train:
          uri: lists/train.txt
          annotation: rttm/{uri}.rttm
          annotated: uems/{uri}.uem
        development:
          uri: lists/dev.txt
          annotation: rttm/{uri}.rttm
          annotated: uems/{uri}.uem
        test:
          uri: lists/test.txt
          annotation: rttm/{uri}.rttm
          annotated: uems/{uri}.uem
      
      Custom_dev2h:
        scope: file
        train:
          uri: lists/train.txt
          annotation: rttm/{uri}.rttm
          # annotated: uem/all.uem
          annotated: uems/{uri}.uem
        development:
          uri: lists/dev2h/2h.txt
          annotation: rttm/{uri}.rttm
          # annotated: uem/all.uem
          annotated: uems/{uri}.uem
        test:
          uri: lists/test.txt
          annotation: rttm/{uri}.rttm
          # annotated: uem/all.uem
          annotated: uems/{uri}.uem